---
- name: EC2 Automation Project
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Debug SSM parameter lookups
      debug:
        msg:
          - "Image ID: {{ lookup('aws_ssm', '/JJTech/ModelBatch/AmazonLinux', region='us-east-1') }}"
          - "Security Group: {{ lookup('aws_ssm', '/JJTech/ModelBatch/Restricted', region='us-east-1') }}"
          - "Subnet ID: {{ lookup('aws_ssm', '/JJTech/ModelBatch/AZa', region='us-east-1') }}"

    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: ec2-automation
        region: us-east-1
        image_id: "{{ lookup('aws_ssm', '/JJTech/ModelBatch/AmazonLinux', region='us-east-1') }}"
        instance_type: t2.micro
        key_name: "{{ lookup('aws_ssm', '/JJTech/ModelBatch/keyname', region='us-east-1') }}"
        vpc_subnet_id: "{{ lookup('aws_ssm', '/JJTech/ModelBatch/AZa', region='us-east-1') }}"
        security_group: "{{ lookup('aws_ssm', '/JJTech/ModelBatch/Restricted', region='us-east-1') }}"
        tags:
          App_Name: model-app
          Business_Unit: sec
          Cost_Center: A250
          Owner: Ib.
          created_by: Ib.
        user_data: |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          service httpd start
          chkconfig httpd on
          yum install wget -y
          wget https://github.com/awanmbandi/aws-real-world-projects/raw/web-appplications-src-code/medlife-health-care.zip -P ~/
          yum install unzip -y
          unzip ~/medlife-health-care.zip
          rm -f /var/www/html/index.html
          cp -rf medlife-master/* /var/www/html/
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 8
              volume_type: gp2
              delete_on_termination: true
              encrypted: true
        state: present
        wait: true
        wait_timeout: 600
